name: Check User in Jenkins

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to check'
        required: true
        type: string

jobs:
  trigger-jenkins:
    runs-on: self-hosted
    
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl "${{ secrets.JENKINS_URL }}/job/check-user/buildWithParameters?username=${{ inputs.username }}"
