# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_pods:
    runs-on: self-hosted
    outputs:
      pod_status: ${{ steps.check.outputs.pod_status }}
    steps:
      - name: Check Kubernetes Pods
        id: check
        run: |
          pod=$(kubectl get pods -A --field-selector=status.phase!=Running -o json | jq '.items | length')
          echo "${pod}"
          echo "pod_status=${pod}" >> "$GITHUB_OUTPUT"


  notification:
    runs-on: ubuntu-latest
    needs: check_pods
    if: ${{ needs.check_pods.outputs.pod_status != '0'}}
    steps:
    - run: echo "${{ env.POD_STATUS }}"
    - name: Post text to a Slack channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "howdy <@channel>!"
